name: Deploy Venti to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
      
        - name: Use Node.js 22
          uses: actions/setup-node@v3
          with:
            node-version: '22'
            cache: 'npm'  

        - name: Install Dependencies
          run: npm install
            
        - name: Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }} # Your EC2 public IP or domain name
            username: ${{ secrets.EC2_USERNAME }} # Your EC2 username 
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                cd /home/admin/ventiebackend 
                git pull origin main
                npm install
                pm2 restart ventiebackend