name: Deploy Venti to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'  

      - name: Install Dependencies
        run: npm install

      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/PASSWITTY/ventiebackend.git

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }} 
          script: |
            cd /home/admin/ventiebackend
            git pull origin main
            npm install
            if pm2 list | grep ventiebackend; then
              pm2 restart ventiebackend
            else
              pm2 start ventiebackend
            fi  
